baseURL = "https://beryju.io"
languageCode = "en-us"
title = "BeryJu.io"
theme = "hello-friend"
disqusShortname = "beryju"
paginate = 5
enableGitInfo = true

[author]
name = "Jens Langhammer"
email = "jens@beryju.org"

[params]
  contentTypeName = "blog"
  defaultTheme = "dark"
  showMenuItems = 3
  showReadingTime = true
[languages]
  [languages.en]
    title = "BeryJu.io"
    subtitle = ""
    keywords = ""
    copyright = ""
    menuMore = "Show more"
    writtenBy = "Written by"
    readMore = "Read more"
    readOtherPosts = "Read other posts"
    newerPosts = "Newer posts"
    olderPosts = "Older posts"
    minuteReadingTime = "min read"
    dateFormatSingle = "2006-01-02"
    dateFormatList = "2006-01-02"

    [languages.en.params.logo]
      logoText = "BeryJu.io"
      logoHomeLink = "/"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "about"
        name = "About"
        url = "https://jela.io"
      [[languages.en.menu.main]]
        identifier = "github"
        name = "GitHub"
        url = "https://github.com/BeryJu"
      [[languages.en.menu.main]]
        identifier = "support_me"
        name = "Support me"
        url = "https://github.com/sponsors/BeryJu"
