[dev]
framework = "hugo"

[build]
publish = "public"
command = "hugo --gc --minify"

[context.production.environment]
HUGO_VERSION = "0.87.0"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

[context.deploy-preview]
command = "hugo --gc --minify --buildFuture -b $DEPLOY_PRIME_URL"

[context.deploy-preview.environment]
HUGO_VERSION = "0.87.0"

[context.branch-deploy]
command = "hugo --gc --minify -b $DEPLOY_PRIME_URL"

[context.branch-deploy.environment]
HUGO_VERSION = "0.87.0"

[context.next.environment]
HUGO_ENABLEGITINFO = "true"

[[redirects]]
  from = "/*"
  to = "https://beryjuorg.netlify.app/.netlify/functions/go-get"
  status = 200
  force = true
  query = {go-get = "1"}

[[redirects]]
  from = "/v2"
  to = "https://beryjuorg.netlify.app/.netlify/functions/oci-proxy"
  status = 200
  force = true

[[redirects]]
  from = "/v2/*"
  to = "https://ghcr.io/v2/beryju/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/js/script.js"
  to = "https://plausible.io/js/plausible.outbound-links.js"
  status = 200
  force = true

[[redirects]]
  from = "/api/event"
  to = "https://analytics.beryju.org/api/event"
  status = 200
  force = true
