[dev]
framework = "hugo"

[build]
publish = "public"
command = "hugo --gc --minify"

[context.production.environment]
HUGO_VERSION = "0.87.0"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

[context.deploy-preview]
command = "hugo --gc --minify --buildFuture -b $DEPLOY_PRIME_URL"

[context.deploy-preview.environment]
HUGO_VERSION = "0.87.0"

[context.branch-deploy]
command = "hugo --gc --minify -b $DEPLOY_PRIME_URL"

[context.branch-deploy.environment]
HUGO_VERSION = "0.87.0"

[context.next.environment]
HUGO_ENABLEGITINFO = "true"

# Working with artifactory

# [[redirects]]
#   from = "/v2/"
#   to = "https://ghcr.registry.beryju.org/v2/"
#   status = 200
#   force = true

# [[redirects]]
#   from = "/v2/*"
#   to = "https://ghcr.registry.beryju.org/v2/beryju/:splat"
#   status = 200
#   force = true

[[redirects]]
  from = "/v2"
  to = "https://beryjuorg.netlify.app/.netlify/functions/docker-v2"
  status = 200
  force = true

[[redirects]]
  from = "/v2/_token"
  to = "https://beryjuorg.netlify.app/.netlify/functions/docker-v2-token"
  status = 200
  force = true

[[redirects]]
  from = "/v2/*"
  to = "https://ghcr.io/v2/beryju/:splat"
  status = 200
  force = true
