name: docker-build

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Get current timestamp
      id: time
      run: echo "::set-output name=time::$(date +'%s')"
    - name: Build and push Docker images
      uses: docker/build-push-action@v2.6.1
      with:
        context: .
        tags: |
          ghcr.io/beryju/beryju.org:latest,
          ghcr.io/beryju/beryju.org:auto-${{ steps.time.outputs.time }}
        push: ${{ github.ref == 'refs/heads/master' }}
